### ISSUE TITLE
Renaming to t3solid

### ISSUE THREAD

**Issue by nexxeln** [OrJDev/create-jd-app#8]
It's your choice really, but I think adding t3 to it would make it easier for people to discover and understand the underlaying technologies.

**Comment by OrJDev** [comment]
This wasn't created as "t3 but for solid", I really like the t3 stack so I added some of its features as addons to jd, however this was created because I thought `npm init solid` was bad and can be improved easily and not because of t3 - also this will contain non t3 related features in the future. I will add t3 to NPM / github keywords & to the readme tho.

**Comment by OrJDev** [comment]
done - https://github.com/OrJDev/create-jd-app/commit/6cc4579880e434b2cdd269eb0db0a87ead6cd5a1#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aa
